#!/usr/bin/env python3
"""Capture an exact, reviewable pip lock from an existing validated venv.

This is intentionally a capture tool, not an updater: it records the working
environment and rejects moving VCS references.  Artifact acquisition and
hash refresh remain an explicit release operation.
"""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path


MOVING_VCS = re.compile(r"git\+[^\s]+@(?![0-9a-f]{40}(?:#|$))")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--python", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--python-contract", required=True)
    args = parser.parse_args()
    completed = subprocess.run(
        [str(args.python), "-m", "pip", "freeze", "--all"],
        check=True,
        capture_output=True,
        text=True,
    )
    lines = sorted(
        (line.strip() for line in completed.stdout.splitlines() if line.strip()),
        key=str.casefold,
    )
    moving = [line for line in lines if MOVING_VCS.search(line)]
    if moving:
        raise SystemExit(f"moving VCS reference in captured environment: {moving[0]}")
    header = [
        "# Generated by scripts/capture_runtime_lock.py from a validated environment.",
        f"# Python contract: {args.python_contract}",
        "# Do not edit manually; refresh through the documented review workflow.",
        "",
    ]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(header + lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
